name: Monitor Copilot PRs

on:
  workflow_run:
    workflows: ["*"]
    types:
      - completed
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write
  actions: read
  checks: read

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false

      - name: Build monitor
        run: go build -o monitor ./cmd/monitor

      - name: Run monitor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: ./monitor
